/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"

static void GPIO_InitStructConfig();
static void EXTI_InitStruct();
static void SPI_Config();
static void SPI_GPIO_Config();


SPI_HandleTypedef_t SPI_HandleStructure;


void EXTI0_IRQHandler()
{
	char msgToSend[]="Hello Word\n";

	if(EXTI->EXTI_PR & 0x1)
	{
		EXTI->EXTI_PR |= (0X1U << 0U);

		SPI_TransmitData_IT(&SPI_HandleStructure, (uint8_t*)msgToSend, strlen(msgToSend));


	}

}


void SPI1_IRQHandler()
{
	SPI_InterruptHandler(&SPI_HandleStructure);

}

int main(void)
{
	GPIO_InitStructConfig();
	EXTI_InitStruct();
	SPI_GPIO_Config();
	SPI_Config();



	for(;;)
	{

	}


}


static void GPIO_InitStructConfig()
{
	GPIO_InitTypeDef_t GPIO_InitStruct={0};

	RCC_CLOCK_GPIOD_ENABLE();															// Clock D activate
	RCC_CLOCK_GPIOA_ENABLE();															// Clock A activate														// Clock SYSCFG activate
	GPIO_InitStruct.pinNumber=GPIO_PIN_12 |GPIO_PIN_13 |GPIO_PIN_14 | GPIO_PIN_15;
	GPIO_InitStruct.Mode=GPIO_MODE_OUTPUT;
	GPIO_InitStruct.Speed=GPIO_OUTPUT_LOW_SPEED;
	GPIO_InitStruct.Otyte=GPIO_OTYPE_PUSH_PULL;
	GPIO_InitStruct.PuPd=GPIO_PUPD_NOPULL_NOPUSH;
	GPIO_Init(GPIOD, &GPIO_InitStruct);
	memset(&GPIO_InitStruct,0,sizeof(GPIO_InitStruct));


	GPIO_InitStruct.pinNumber=GPIO_PIN_0;
	GPIO_InitStruct.Mode=GPIO_MODE_INPUT;
	GPIO_InitStruct.PuPd=GPIO_PUPD_PULLDOWN;
	GPIO_Init(GPIOA, &GPIO_InitStruct);//configuration





}
static void EXTI_InitStruct()
{
	EXTI_InitTypedef_t EXTI_InitStruct={0};
	RCC_SYSCFG_CLK_ENABLE();

	EXTI_LineConfig(EXTI_PortSource_GPIOA, EXTI_LineSource_0);


	EXTI_InitStruct.EXTI_LineCmd=ENABLE;
	EXTI_InitStruct.EXTI_LineNumber=EXTI_LineSource_0;
	EXTI_InitStruct.EXTI_Mode=EXTI_MODE_INTERRUPT;
	EXTI_InitStruct.TriggerSelection=EXTI_TRIGGER_MODE_RISING;
	EXTI_Init(&EXTI_InitStruct);

	NVIC_EnableInterrupt(EXTI0_IRQNumber);
}

static void SPI_Config()
{

	RCC_SP1_CLK_ENABLE();
	SPI_HandleStructure.Instance=SPI1;
	SPI_HandleStructure.Init.BaudRate=SPI_BAUDRATE_DIV8;
	SPI_HandleStructure.Init.BusConfig=SPI_BUS_FullDuplex;
	SPI_HandleStructure.Init.CPHA=SPI_CPHA_FIRST;
	SPI_HandleStructure.Init.CPOL=SPI_CPOL_LOW;
	SPI_HandleStructure.Init.DFF_Format=SPI_DFF_8BITS;
	SPI_HandleStructure.Init.Frame_Format=SPI_FRAMEFORMANT_MSB;
	SPI_HandleStructure.Init.Mode=SPI_MODE_MASTER;
	SPI_HandleStructure.Init.SSM_CMD=SPI_SSM_ENABLE;



	SPI_Init(&SPI_HandleStructure);
	NVIC_EnableInterrupt(SPI1_IRQNumber);


	SPI_PeripheralCmd(&SPI_HandleStructure, ENABLE);





}
static void SPI_GPIO_Config()
{
	GPIO_InitTypeDef_t GPIO_InitStruct = {0};

	GPIO_InitStruct.pinNumber=GPIO_PIN_5 | GPIO_PIN_7;  // PA5=>SCLK PA7=>MOSI
	GPIO_InitStruct.Mode=GPIO_MODE_AF;
	GPIO_InitStruct.Otyte=GPIO_OTYPE_PUSH_PULL;
	GPIO_InitStruct.PuPd=GPIO_PUPD_NOPULL_NOPUSH;
	GPIO_InitStruct.Speed=GPIO_OUTPUT_VERY_HIGH_SPEED;
	GPIO_InitStruct.Alternate=GPIO_AF5;

	GPIO_Init(GPIOA, &GPIO_InitStruct);


}
